### PR TITLE
Fixed issue with typo in simplex.html.erb that prevented app from sta…

### PR DESCRIPTION
**Pull request by h6y3**
This is to address #45

### CODE REVIEW

**Comment by h6y3** [comment]
@lumandra Can you review my pull request and let me know if this is okay?

**Comment by lumandra** [comment]
Sorry @h6y3, but I can't reproduce this issue. I check app on start in development mode with previous assets, after assets: precompile (with previous assets in public), after assets: precompile (with public cleansing), and launch in production mode. All this was done on the master branch to reproduce the issue. Can you send to me screenshot with error or something additional information that can help me to reproduce issue?
Screenshot with app start without error

**Comment by h6y3** [comment]
> Sorry @h6y3, but I can't reproduce this issue. I checked app on start in development mode with previous assets, after assets: precompile (with previous assets in public), after assets: precompile (with public cleansing), and launch in production mode. All this was done on the master branch to reproduce the issue. Can you send to me screenshot with error or something additional information that can help me to reproduce issue?
> Screenshot with app start without error

Sorry, it starts @lumandra but if you hit http://localhost:3000 you should see an issue.

**Comment by h6y3** [comment]
OK, I can't reproduce it either now.  :)  I will close.  Not sure what I did or what happened.  Staging works again @lumandra.  I will merge your other PR and see if there are any issues.

**Pull request closed without merging**
